/* =========================================================================
   SPEAKEASY — French (Canada) copy.

   One key per string, matching the `data-i18n*` attributes in the HTML and
   the t('…') calls in js/site.js and js/events.js. Anything missing here
   simply stays in English, so the site never breaks on a half-finished
   translation. Prices, dates and hours are formatted the Canadian way
   (18 $, 22 h 30) — the "$ after the number" rule lives in css/styles.css.
   ========================================================================= */
'use strict';

export default {

  /* ---------------- page titles + social/meta descriptions ---------------- */
  'meta.home.title': 'Speakeasy Tapas Lounge · Marché By, Ottawa',
  'meta.home.desc': 'Une adresse cachée pour la table, la musique et les célébrations, dans le marché By d’Ottawa. Cocktails d’auteur, tapas et musique live tous les soirs. 55, rue York · 613-241-6221.',
  'meta.drinks.title': 'Le bar · Speakeasy Tapas Lounge',
  'meta.drinks.desc': '13 cocktails signature, une carte des vins choisie et de la bière locale en fût au Speakeasy Tapas Lounge.',
  'meta.menu.title': 'Menu · Speakeasy Tapas Lounge',
  'meta.menu.desc': 'À partager, souper et desserts au Speakeasy Tapas Lounge — tataki de bœuf, tartare de thon, confit de canard, rigatonis à la bolognaise, crème brûlée et plus.',
  'meta.events.title': 'Événements · Speakeasy Tapas Lounge',
  'meta.events.desc': 'Musique live tous les soirs, rencontres éclair, humour et plus au Speakeasy Tapas Lounge. Balayez pour garder les soirées qui vous plaisent.',
  'meta.private.title': 'Événements privés · Speakeasy Tapas Lounge',
  'meta.private.desc': 'Mariages, événements d’entreprise, vitrines et fêtes thématiques au Speakeasy Tapas Lounge, dans le marché By d’Ottawa.',
  'meta.tour.title': 'Visite 3D · Speakeasy Tapas Lounge',
  'meta.tour.desc': 'Faites une visite interactive en 3D du Speakeasy Tapas Lounge, dans le marché By d’Ottawa.',
  'meta.visit.title': 'Nous visiter et réserver · Speakeasy Tapas Lounge',
  'meta.visit.desc': 'Visitez le Speakeasy Tapas Lounge au 55, rue York, à Ottawa. Réservations par téléphone au 613-241-6221. Heures d’ouverture, carte et coordonnées.',

  /* ---------------- header, footer, shared buttons ---------------- */
  'a11y.skip': 'Aller au contenu',
  'nav.home': 'Accueil',
  'nav.drinks': 'Bar',
  'nav.menu': 'Menu',
  'nav.events': 'Événements',
  'nav.private': 'Événements privés',
  'nav.tour': 'Visite 3D',
  'nav.visit': 'Nous visiter',
  'nav.book': 'Réserver',
  'nav.bookTable': 'Réserver une table',
  'nav.reserveCall': 'Réserver · 613-241-6221',
  'nav.callLong': 'Appeler le 613-241-6221',
  'nav.brand': 'Speakeasy Tapas Lounge — accueil',
  'nav.sections': 'Sections',
  'nav.mobile': 'Mobile',
  'nav.footer': 'Pied de page',
  'nav.openMenu': 'Ouvrir le menu',
  'nav.language': 'Langue',
  'foot.address': '55, rue York, Ottawa · K1N 9B7',
  'foot.fine': '© <span id="year"></span> Speakeasy Tapas Lounge · Marché By, Ottawa · À consommer avec modération.',
  'cta.reserve': 'Réserver une table',
  'cta.menu': 'Voir le menu',

  /* ---------------- home: door intro + hero ---------------- */
  'intro.aria': 'Entrer dans le Speakeasy',
  'intro.shh': '<span>C</span><span>h</span><span>u</span><span>t</span><span>…</span>',
  'intro.word': 'Que ça reste entre nous.',
  'intro.enter': 'touchez pour entrer',
  'intro.skip': 'Passer&nbsp;→',
  'hero.coin': 'Faites-la tourner',
  'hero.crestAlt': 'Blason du Speakeasy Tapas Lounge',
  'hero.eyebrow': 'Marché By · Ottawa · L’esprit de la prohibition',
  'hero.tag': '« Ça ne peut être qu’ici »',
  'hero.scroll': 'défiler',
  'hero.scrollAria': 'Défiler pour explorer',

  /* ---------------- home: the six wax seals ---------------- */
  'stamp.food': 'Cuisine',
  'stamp.music': 'Musique live',
  'stamp.comedy': 'Humour',
  'stamp.concerts': 'Concerts',
  'stamp.cocktails': 'Cocktails',
  'stamp.private': 'Événements privés',

  /* ---------------- home: pull up a seat ---------------- */
  'home.about.kicker': 'Les règles de la maison',
  'home.about.title': 'Prenez<br><em>place.</em>',
  'home.about.lead': 'Niché dans le marché By d’Ottawa, le Speakeasy Tapas Lounge est un restaurant élégant et une salle de spectacle où la lumière reste tamisée et où la soirée s’étire.',
  'home.about.body': 'Des assiettes d’inspiration internationale, des cocktails d’auteur servis avec l’aplomb de la prohibition, des spectacles tous les soirs et une salle aux chandelles qui a tout d’un secret bien gardé. Tirez-vous une chaise — <em>ça ne peut être qu’ici.</em>',
  'home.about.stat1': 'Tous les soirs',
  'home.about.stat1sub': 'Musique live dès 19 h',
  'home.about.stat2sub': 'Cocktails signature',
  'home.about.stat3': '55, rue York',
  'home.about.stat3sub': 'Marché By',

  /* ---------------- home: the doorman ---------------- */
  'home.host.kicker': 'À la porte',
  'home.host.title': 'L’homme au<br><em>costume jaune.</em>',
  'home.host.lead': 'Tout speakeasy a son portier. Le nôtre ne demande aucun mot de passe — il sourit, tient la porte et vous indique le tapis rouge.',
  'home.host.body': 'Si vous l’apercevez rue York, vous êtes au bon endroit. Saluez-le, prenez une photo et entrez — les chandelles sont déjà allumées.',
  'home.host.caption': 'La plupart des soirs, devant le 55, rue York',
  'home.host.cta': 'Trouver la porte',
  'home.host.link': 'Voir ce qui joue ce soir →',
  'home.host.imgAlt': 'Le portier du Speakeasy, en costume jaune et masque vert, devant le 55, rue York',

  /* ---------------- home: reviews ---------------- */
  'home.reviews.kicker': 'Le bouche-à-oreille',
  'home.reviews.title': 'Ce qu’on en dit',
  'home.reviews.on': 'sur Google',
  'home.reviews.read': 'Lire nos avis Google',
  'home.reviews.leave': 'Laisser un avis',
  'home.reviews.quote': '« Ajoutez ici un vrai avis Google. »',
  'home.reviews.cite': '— Nom du client',
  'home.reviews.note': 'La note et les citations sont des exemples — remplacez-les par vos vrais avis Google (voir le README).',

  /* ---------------- home: Instagram ---------------- */
  'home.insta.kicker': 'Suivez-nous',
  'home.insta.intro': 'La salle, les assiettes, les gens et le set du soir. Venez nous trouver.',
  'home.insta.follow': 'Suivez-nous sur Instagram',
  'home.insta.alt1': 'Derrière le bar',
  'home.insta.alt2': 'Une chanteuse sur la scène du Speakeasy',
  'home.insta.alt3': 'L’équipe de cuisine',
  'home.insta.alt4': 'Un saxophoniste sous l’enseigne du Speakeasy',
  'home.insta.alt5': 'Le portier en haut de l’escalier éclairé aux chandelles',
  'home.insta.alt6': 'Une tablée d’assiettes du Speakeasy',
  'home.insta.alt7': 'Huîtres du marché et bulles',
  'home.insta.alt8': 'Une violoncelliste en pleine prestation',
  'home.insta.alt9': 'L’enseigne du Speakeasy dans le marché By',

  /* ---------------- lightbox ---------------- */
  'lb.viewer': 'Visionneuse de photos',
  'lb.close': 'Fermer',
  'lb.prev': 'Précédent',
  'lb.next': 'Suivant',

  /* ---------------- the bar ---------------- */
  'drinks.kicker': 'Le bar',
  'drinks.h1': 'Le bar',
  'drinks.lead': 'Treize cocktails signature, une cave choisie et de la bière locale bien froide — servis avec l’aplomb de la prohibition.',
  'drinks.signature': 'Cocktails signature',
  'drinks.signature.sub': 'Treize créations, chacune avec un clin d’œil à l’époque.',
  'drinks.signature.range': 'Tous entre 15 et 18 $',
  'drinks.corpse.ing': 'Gin · Cointreau · Lillet Blanc · citron · rinçage à l’absinthe',
  'drinks.corpse.note': 'Vif, herbacé et dangereusement facile — le remède original du lendemain.',
  'drinks.capone.ing': 'Bourbon · vermouth doux · amaro · bitters à l’orange',
  'drinks.capone.note': 'Puissant et ténébreux. Remué, jamais pressé — comme l’homme lui-même.',
  'drinks.maple.ing': 'Whisky de seigle · érable · citron · bitters aux noix',
  'drinks.maple.note': 'Le réconfort canadien dans une coupe, sucré et un brin sauvage.',
  'drinks.lagoon.ing': 'Vodka · curaçao bleu · limonade fraîche',
  'drinks.lagoon.note': 'Bleu électrique et infiniment rafraîchissant. Notre sirène maison.',
  'drinks.oldfashioned.ing': 'Seigle · érable · Angostura · zeste d’orange',
  'drinks.oldfashioned.note': 'Une version nordique du classique. Franc en alcool et réconfortant.',
  'drinks.margarita.ing': 'Téquila · fruit de la passion · lime · agave',
  'drinks.margarita.note': 'Tropical, acidulé et ensoleillé — de petites vacances dans un verre.',
  'drinks.espresso.ing': 'Vodka · espresso fraîchement tiré · liqueur de café',
  'drinks.espresso.note': 'On se réveille, puis on danse. Soyeux dessus, mordant dessous.',
  'drinks.velvet.ing': 'Gin · fleur de sureau · fruit de la passion · prosecco',
  'drinks.velvet.note': 'Soyeux et floral, avec une finale pétillante.',
  'drinks.twilight.ing': 'Gin · crème de violette · agrumes · mousseux',
  'drinks.twilight.note': 'L’heure violette, mise en bouteille. Parfumé et mystérieux.',
  'drinks.spritz.ing': 'Aperol · prosecco · soda · orange',
  'drinks.spritz.note': 'L’apéro de l’heure dorée — amer, pétillant, léger.',
  'drinks.french75.ing': 'Gin · champagne · citron · sucre',
  'drinks.french75.note': 'Nommé d’après un canon de campagne. Vif, festif, plus costaud qu’il n’en a l’air.',
  'drinks.boulevardier.ing': 'Bourbon · Campari · vermouth doux',
  'drinks.boulevardier.note': 'Un Negroni en manteau de fourrure. Riche et doux-amer.',
  'drinks.clover.ing': 'Gin · framboise · citron · mousse soyeuse',
  'drinks.clover.note': 'Le rose d’avant la prohibition. Fruité, mousseux et élégant.',
  'drinks.bubbles': 'Bulles et rosé',
  'drinks.white': 'Blancs',
  'drinks.red': 'Rouges',
  'drinks.tap': 'En fût et en canette',
  'drinks.wine.champagne': 'Champagne brut',
  'drinks.wine.rose': 'Rosé de Provence',
  'drinks.reg.veneto': '· Vénétie, Italie',
  'drinks.reg.france': '· France',
  'drinks.reg.italy': '· Italie',
  'drinks.reg.california': '· Californie',
  'drinks.reg.tuscany': '· Toscane',
  'drinks.reg.draught': '· en fût, Ottawa',
  'drinks.reg.bottle': '· bouteille',
  'drinks.reg.can': '· canette',
  'drinks.foot': 'Prix en dollars canadiens · formats verre / bouteille. Demandez à votre serveur les suggestions du soir.',

  /* ---------------- the menu ---------------- */
  'menu.kicker': 'La cuisine',
  'menu.h1': 'Le menu',
  'menu.lead': 'De petites assiettes à partager, des plats qui valent le détour et un secret sucré pour finir. Passez de l’un à l’autre.',
  'menu.tabsAria': 'Sections du menu',
  'menu.tab.shareables': 'À partager',
  'menu.tab.dinner': 'Souper',
  'menu.tab.desserts': 'Desserts',
  'menu.earth': 'De la terre',
  'menu.sea': 'De la mer',
  'menu.garden': 'Du jardin',
  'menu.favourite': 'Coup de cœur de la maison',
  'menu.tataki': 'Tataki de bœuf',
  'menu.tataki.d': 'Bœuf de première qualité saisi, ponzu, échalote croustillante, pousses.',
  'menu.slider.d': 'Mini-burger de bœuf maison, cheddar vieilli, sauce secrète, brioche grillée.',
  'menu.slider.alt': 'Mini-burgers de bœuf maison et frites assaisonnées',
  'menu.rolls': 'Rouleaux impériaux au confit de canard',
  'menu.rolls.d': 'Rouleaux croustillants de canard confit, sauce hoisin et prune.',
  'menu.rolls.alt': 'Rouleaux impériaux au confit de canard avec sauce chili',
  'menu.tartare': 'Tartare de thon',
  'menu.tartare.d': 'Thon qualité sushi, avocat, sésame et soya, fleur comestible, croustilles de wonton.',
  'menu.tartare.alt': 'Tartare de thon à l’avocat et croustilles de wonton dans un verre à martini',
  'menu.scallops': 'Pétoncles et racines',
  'menu.scallops.d': 'Pétoncles saisis, purée de céleri-rave, beurre noisette.',
  'menu.scallops.alt': 'Pétoncles saisis avec purée de céleri-rave et betteraves',
  'menu.tempura': 'Crevettes tempura',
  'menu.tempura.d': 'Crevettes en tempura ultralégère, aïoli au yuzu.',
  'menu.oysters': 'Huîtres du marché',
  'menu.oysters.d': 'Sélection du jour, mignonette classique, citron.',
  'menu.oysters.p': '3,50 $ ch.',
  'menu.oysters.alt': 'Plateau d’huîtres du marché sur glace',
  'menu.burrata': 'Bruschetta burrata et tomate',
  'menu.burrata.d': 'Burrata crémeuse, tomate ancestrale, basilic, pain au levain grillé.',
  'menu.fries': 'Frites tajine du Speakeasy',
  'menu.fries.d': 'Frites coupées à la main, aïoli à l’harissa, fines herbes, copeaux de parmesan.',
  'menu.crostini': 'Crostinis poire et brie',
  'menu.crostini.d': 'Brie chaud, poire pochée, miel, noix grillées.',
  'menu.halloumi': 'Halloumi au miel',
  'menu.halloumi.d': 'Halloumi grillé, miel piquant, flocons de piment, menthe fraîche.',
  'menu.dinnerHours': 'Souper servi <strong>mar.–jeu. 16 h – 22 h 30</strong> · <strong>ven.–sam. 16 h – minuit</strong>',
  'menu.peri': 'Poulet peri-peri',
  'menu.peri.d': 'Demi-poulet, marinade peri-peri, citron grillé, frites coupées à la main.',
  'menu.duck': 'Confit de canard',
  'menu.duck.d': 'Cuisse de canard croustillante, gastrique aux cerises, purée de pommes de terre soyeuse.',
  'menu.salmon': 'Saumon de l’Atlantique',
  'menu.salmon.d': 'Saumon poêlé, beurre blanc aux herbes, légumes de saison.',
  'menu.striploin': 'Contre-filet New York aux herbes',
  'menu.striploin.d': 'Contre-filet de 10 oz, chimichurri, légumes-racines du marché rôtis.',
  'menu.rigatoni': 'Rigatonis à la bolognaise',
  'menu.rigatoni.d': 'Ragù de bœuf braisé longuement, burrata déchirée, pain grillé.',
  'menu.cannelloni': 'Cannellonis à l’aubergine',
  'menu.cannelloni.d': 'Aubergine rôtie, ricotta, pomodoro, basilic. <em>Végétarien.</em>',
  'menu.sweet': 'Douces finales',
  'menu.sweet.sub': 'Le dernier secret de la soirée.',
  'menu.brulee': 'Crème brûlée à l’Earl Grey',
  'menu.brulee.d': 'Crème infusée à la bergamote, sucre caramélisé craquant.',
  'menu.affogato.d': 'Gelato à la vanille noyé d’espresso chaud, brisures d’amaretti.',
  'menu.sorbet': 'Sorbet mangue et bourbon',
  'menu.sorbet.d': 'Sorbet éclatant à la mangue, un soupçon de bourbon.',
  'menu.cheesecake': 'Gâteau au fromage aux pacanes',
  'menu.cheesecake.d': 'Gâteau au fromage, pacanes au beurre noisette, caramel salé.',
  'menu.reel.title': 'Un avant-goût de la soirée',
  'menu.reel.sub': 'Musique live. Tapas. Ambiance.',

  /* ---------------- events + the swipe deck ---------------- */
  'events.kicker': 'Tous les soirs sur scène',
  'events.h1': 'Événements',
  'events.lead': 'Musique live tous les soirs dès 19 h — et des soirées spéciales qui valent le détour. <strong>Balayez vers la droite celles qui vous tentent.</strong>',
  'events.pass': 'Passer',
  'events.undo': 'Annuler',
  'events.yes': 'Ça m’intéresse',
  'events.hint': 'Faites glisser une carte — ou utilisez ✕ / ♥ (ou les flèches ← →).',
  'events.yesStamp': 'Oui',
  'events.noStamp': 'Non',
  'events.saved': 'Super — « {title} » est gardée',
  'events.none': 'Aucun coup de cœur — c’est permis.',
  'events.noneNote': 'Pas d’humeur ce soir ? Le bar est toujours ouvert.',
  'events.likedOne': 'Une soirée vous tente.',
  'events.likedMany': '{n} soirées vous tentent.',
  'events.likedNote': 'Nous les avons gardées ci-dessous. Appelez pour réserver, ou ajoutez-les à votre calendrier.',
  'events.callReserve': 'Appeler pour réserver',
  'events.addCal': 'Ajouter au calendrier',
  'events.again': 'Recommencer',
  'events.ics': 'Fichier calendrier téléchargé',
  'events.reel.kicker': 'Sur scène',
  'events.reel.title': 'En direct, presque tous les soirs',
  'events.reel.sub': 'Un aperçu de la salle quand le set commence.',

  /* ---------------- private events ---------------- */
  'private.kicker': 'Célébrez chez nous',
  'private.h1': 'Événements privés',
  'private.lead': 'Prenez la salle pour la soirée. Quatre façons de célébrer — chacune taillée sur mesure.',
  'private.details': 'Détails',
  'private.plan': 'Planifier votre événement',
  'private.call': 'ou appelez le 613-241-6221 →',
  'private.pkg1.title': 'Expérience événementielle premium',
  'private.pkg1.for': 'Événements d’entreprise · cocktails · rassemblements',
  'private.pkg1.li1': 'Menu entièrement personnalisable',
  'private.pkg1.li2': 'Cocktails de bienvenue à l’arrivée',
  'private.pkg1.li3': 'Formules bar ouvert',
  'private.pkg1.extra': 'Idéal pour les lancements, les célébrations d’équipe et les soirées de réseautage, dans une salle qui sait déjà recevoir.',
  'private.pkg2.title': 'Repas intime de célébration',
  'private.pkg2.for': 'Mariages · dîners de répétition · brunchs · déjeuners',
  'private.pkg2.li1': 'Repas privés et menus sur mesure',
  'private.pkg2.li2': 'Accords mets et vins choisis',
  'private.pkg2.li3': 'Aux chandelles, intime et chaleureux',
  'private.pkg2.extra': 'Pour les moments qui comptent le plus — une célébration assise, avec un menu bâti autour de votre table.',
  'private.pkg3.title': 'Vitrine artistique et excellence culinaire',
  'private.pkg3.for': 'Expositions · vernissages · événements culturels',
  'private.pkg3.li1': 'Aménagement façon galerie',
  'private.pkg3.li2': 'Service traiteur et dégustations',
  'private.pkg3.li3': 'Soutien à l’éclairage et à la promotion',
  'private.pkg3.extra': 'Transformez le lounge en galerie le temps d’une soirée, avec une cuisine et un éclairage pensés autour des œuvres.',
  'private.pkg4.title': 'Soirée thématique et aventure culinaire',
  'private.pkg4.for': 'Fêtes thématiques · célébrations des Fêtes',
  'private.pkg4.li1': 'Décor et cocktails sur mesure',
  'private.pkg4.li2': 'Menu personnalisé',
  'private.pkg4.li3': 'DJ et spectacles sur scène',
  'private.pkg4.extra': 'Allez-y à fond. Choisissez un thème et nous bâtirons la soirée autour — de la verrerie à la trame musicale.',
  'private.up.kicker': 'Un deuxième espace',
  'private.up.title': 'L’étage est<br><em>à vous.</em>',
  'private.up.lead': 'Au-dessus du lounge se trouve une salle plus lumineuse — brique blanche, petite scène et sonorisation à elle. Louez-la seule, ou prenez les deux étages pour une plus grande soirée.',
  'private.up.li1': 'Privée, à l’écart de la salle principale',
  'private.up.li2': 'Scène et sonorisation pour spectacles, vitrines ou conférences',
  'private.up.li3': 'Réceptions debout, repas assis ou ateliers',
  'private.up.li4': 'Disponible en complément du lounge du rez-de-chaussée',
  'private.up.cta': 'Informez-vous sur l’étage',
  'private.up.link': 'Voir les dates et les configurations →',

  /* ---------------- 3D tour ---------------- */
  'tour.kicker': 'Parcourez la salle',
  'tour.h1': 'Visite 3D de la salle',
  'tour.lead': 'Explorez le bar, la scène et la salle à manger dans une visite interactive en 3D — puis imaginez-y votre prochain événement privé.',
  'tour.badge': 'Glissez pour regarder · WASD / joystick pour marcher',
  'tour.fs': 'Plein écran',
  'tour.fsAria': 'Basculer en plein écran',
  'tour.frameTitle': 'Speakeasy Tapas Lounge — visite 3D',
  'tour.setupsAria': 'Configurations de la salle',
  'tour.setup.dinner': 'Repas intime',
  'tour.setup.dinner.d': 'Assis · jusqu’à 60',
  'tour.setup.cocktail': 'Réception cocktail',
  'tour.setup.cocktail.d': 'Debout · jusqu’à 100',
  'tour.setup.showcase': 'Vitrine artistique',
  'tour.setup.showcase.d': 'Galerie · plancher ouvert',
  'tour.setup.full': 'Plein écran ↗',
  'tour.setup.full.d': 'Nouvel onglet',
  'tour.note': 'Changez de configuration pour voir la salle se réaménager en direct. Ordinateur : glissez pour regarder, WASD pour marcher. Téléphone : joystick pour marcher, glissez pour regarder.',
  'tour.booking.kicker': 'Réservez la salle',
  'tour.booking.title': 'Réservez-la pour<br><em>votre soirée.</em>',
  'tour.booking.lead': 'Dites-nous à quoi ressemblera la soirée et nous retiendrons la date. Nous répondons le jour même — ou appelez, et tout se règle en une minute.',
  'tour.booking.li1': 'Salle entière ou section privée',
  'tour.booking.li2': 'Menus sur mesure et cocktails de bienvenue',
  'tour.booking.li3': 'Musique live, DJ ou votre propre programmation',
  'tour.booking.prefer': 'Vous préférez parler à quelqu’un ?',
  'tour.form.title': 'Demander une date',
  'tour.form.notes': 'Autre chose',
  'tour.form.notesPh': 'Occasion, horaire, musique…',
  'tour.form.submit': 'Demander cette date',
  'tour.opt.dinner': 'Repas intime — assis, jusqu’à 60',
  'tour.opt.cocktail': 'Réception cocktail — debout, jusqu’à 100',
  'tour.opt.showcase': 'Vitrine artistique — galerie',
  'tour.opt.unsure': 'Je ne sais pas encore',

  /* ---------------- visit & reserve ---------------- */
  'visit.kicker': 'Trouvez la porte',
  'visit.h1': 'Nous visiter et réserver',
  'visit.lead': 'Réservations par téléphone. Sans réservation, bienvenue aussi. Cherchez l’auvent rouge, rue York.',
  'visit.checking': 'Vérification des heures…',
  'visit.address': '55, rue York<br>Ottawa (Ontario) · K1N 9B7',
  'visit.opentable': 'Réserver sur OpenTable',
  'visit.orPhone': 'Ou par téléphone —',
  'visit.hoursCaption': 'Heures d’ouverture',
  'visit.note.title': 'Écrivez-nous',
  'visit.note.hint': 'Questions, demandes pour un événement privé, ou simplement pour dire bonjour.',
  'visit.note.send': 'Envoyer le message',
  'visit.news.title': 'Joignez-vous à la liste',
  'visit.news.hint': 'Spectacles secrets, menus de saison et, à l’occasion, un mot de passe. Pas de pourriel.',
  'visit.news.label': 'Adresse courriel',
  'visit.news.ph': 'vous@courriel.com',
  'visit.news.submit': 'S’abonner',
  'visit.mapTitle': 'Speakeasy Tapas Lounge — carte',
  'visit.mapFallback': '55, rue York, Ottawa · <a href="https://maps.google.com/?q=55+York+Street+Ottawa+ON+K1N+9B7" target="_blank" rel="noopener">Ouvrir dans Maps</a>',
  'visit.know.kicker': 'Avant de venir',
  'visit.know.title': 'Bon à savoir',
  'visit.know1.t': 'Comment nous trouver',
  'visit.know1.d': 'En plein cœur du marché By. Stationnement sur la rue York, et le garage du marché est à deux minutes à pied.',
  'visit.know2.t': 'Réservations',
  'visit.know2.d': 'Par téléphone — nous gardons des tables pour la soirée et pouvons habituellement asseoir au bar les visiteurs sans réservation.',
  'visit.know3.t': 'Restrictions alimentaires',
  'visit.know3.d': 'Des options végétariennes à chaque menu. Mentionnez vos allergies au moment de réserver et la cuisine s’adaptera.',
  'visit.know4.t': 'Grands groupes',
  'visit.know4.d': 'Six personnes ou plus ? Appelez à l’avance. Pour une soirée privée, voyez les <a class="link-underline" href="private.html">événements privés</a> — y compris la salle à l’étage.',
  'visit.know5.t': 'Musique live',
  'visit.know5.d': 'Tous les soirs dès 19 h, sans frais d’entrée. Appelez pour connaître la programmation du soir.',
  'visit.know6.t': 'Cartes-cadeaux',
  'visit.know6.d': 'Offertes sur place — la bonne réponse pour la personne qui a déjà tout.',

  /* ---------------- forms, toasts, hours ---------------- */
  'form.name': 'Nom',
  'form.email': 'Courriel',
  'form.message': 'Message',
  'form.date': 'Date',
  'form.guests': 'Invités',
  'form.setup': 'Configuration',
  'form.err': 'Veuillez remplir les champs en surbrillance.',
  'form.errEmail': 'Une adresse courriel valide, s’il vous plaît.',
  'form.thanks': 'Merci — nous vous reviendrons sous peu.',
  'form.subscribed': 'Vous êtes sur la liste. Bienvenue dans le cercle.',
  'form.requested': 'Demande envoyée — nous confirmerons par courriel aujourd’hui.',
  'mail.enquiry': 'Demande depuis le site web',
  'mail.private': 'Demande d’événement privé',
  'toast.sent': 'Message envoyé · n’en parlez à personne',
  'toast.subscribed': 'Inscription faite · bienvenue',
  'toast.requested': 'Date demandée · nous vous reviendrons',
  'toast.password': 'Mot de passe accepté. N’en parlez à personne.',
  'hours.openNow': 'Ouvert',
  'hours.until': 'jusqu’à',
  'hours.closed': 'Fermé',
  'hours.opens': 'ouvre',
  'hours.today': 'aujourd’hui',
  'hours.midnight': 'Minuit',
  'hours.midnightLower': 'minuit',
};
